"""Prompt templates for AIDLC finalization passes.

Each constant is a full prompt template with {placeholders} for project-specific
context injection. The Finalizer class fills these before sending to the
provider.

NOTE: ``ssot``, ``security``, and ``abend`` passes were removed in the
core-focus audit because their semantics had drifted (vague objectives, no
clear definition of done). New prompts will be reintroduced once their scope
is nailed down. Keep this file small until then.
"""

# Available passes in execution order
PASS_ORDER = ["docs", "cleanup"]

PASS_DESCRIPTIONS = {
    "docs": "Documentation consolidation — rewrite docs to reflect current reality",
    "cleanup": "Code cleanup — formatting, dead code, file size, consistency",
}


DOCS_PROMPT = """\
You are performing a full documentation review and consolidation.

## Project Context
{project_context}

## Objective

Rewrite all documentation to reflect the current state of the codebase.

### Rules
- Documentation only — do not refactor code
- All docs must be Markdown (.md)
- Critical docs live in root (README.md only)
- Supporting docs live in /docs
- BRAINDUMP.md is the customer's voice — never rewrite it; only reference it
- If docs are wrong, outdated, duplicated, or misleading — fix them
- If a doc provides no value — delete it
- If multiple docs overlap — consolidate

### Process
1. Audit the entire repo to understand what the system actually does today
2. Inventory all existing docs — are they accurate, needed, in the right place?
3. Enforce clean structure: README.md (root), everything else in /docs
4. Rewrite to reflect current reality. Remove references to non-existent files, old workflows, deprecated features
5. Validate every statement against actual code — if you can't prove it, don't document it
6. Ensure docs cover: setup, architecture, data models, integrations, configuration, deployment

### README.md Should Be
- What the repo is
- How to run it locally
- Deployment basics
- Where to find deeper docs (/docs)

### Output
Rewrite docs in-place. Delete obsolete docs. Write a summary of changes to
`docs/audits/docs-consolidation.md` explaining what was added, deleted, and consolidated.
Do not commit.
"""


CLEANUP_PROMPT = """\
You are performing a code quality cleanup pass on this repository.

## Project Context
{project_context}

## Git Diff Summary (main...HEAD)
{diff_summary}

## Objective

Bring the repo to a clean, consistent, maintainable state.

### Scope
1. **Dead code** — Remove unused imports, commented-out blocks, stale experiments
2. **Documentation in code** — Add short comments where intent is not obvious. Prefer "why" over "what". Remove outdated comments
3. **Consistency** — Normalize naming patterns, formatting, imports
4. **File size** — Flag files over 500 lines. Extract helpers where logical, but avoid over-splitting
5. **Duplicate utilities** — Consolidate shared logic

### Rules
- Repo must build and run cleanly after cleanup
- No behavioral changes
- No feature additions
- Linting and formatting should pass

### Output
Make cleanup changes in-place. Write a summary of what was cleaned to
`docs/audits/cleanup-report.md` including:
- Dead code removed
- Files refactored
- Files still over 500 LOC (with justification or flagged for follow-up)
- Consistency changes made

Do not commit.
"""


FUTURES_TEMPLATE = """\
# AIDLC Futures — Preparing for Next Round

*Auto-generated by AIDLC finalization on {date}*

## What Was Done This Run

- **Run ID**: {run_id}
- **Issues planned**: {total_issues}
- **Issues implemented**: {issues_implemented}
- **Issues verified**: {issues_verified}
- **Issues failed**: {issues_failed}
- **Finalization passes completed**: {passes_completed}

## Audit Reports

{audit_report_links}

## Preparing for Next Run

1. Update `BRAINDUMP.md` with what you want next — that is the single source of truth
2. Review and update supporting docs (`README.md`, `ARCHITECTURE.md`, `DESIGN.md`, optional `ROADMAP.md`)
3. Address any critical findings in the audit reports above
4. Run `aidlc run` for the next development cycle

## Tips for a Productive Next Run

- **BRAINDUMP.md is the contract** — be specific about what you want
- **Acceptance criteria matter** — the implementer tests against them
- **Optional roadmap** — use `ROADMAP.md` for milestone tracking if your team prefers phases
- **Review the plan first** — use `aidlc run --plan-only` to review before implementing

## Repo State

- **Branch**: {branch}
- **Date**: {date}
- **Project type**: {project_type}
"""
