"""Audit output and conflict rendering engine.

The auditor is read-only by design: it writes STATUS.md (a generated artifact)
and audit_result.json. It never overwrites user-owned docs (BRAINDUMP.md,
ARCHITECTURE.md, ROADMAP.md, DESIGN.md), since those are the customer's voice.
"""

import json
import re

from ..audit_models import AuditConflict, CoverageInfo, ModuleInfo, TechDebtItem
from .constants import EXCLUDE_DIRS


class AuditOutputEngine:
    """Renders docs, detects conflicts, and writes audit artifacts."""

    def __init__(self, auditor):
        self.auditor = auditor

    @property
    def project_root(self):
        return self.auditor.project_root

    @property
    def logger(self):
        return self.auditor.logger

    def generate_docs(self, result) -> None:
        """Write STATUS.md (generated artifact) to project root."""
        status_path = self.project_root / "STATUS.md"
        status_content = self.render_status_doc(result)
        status_path.write_text(status_content)
        result.generated_docs.append("STATUS.md")
        self.logger.info(f"Generated {status_path}")

    def render_status_doc(self, result) -> str:
        """Render STATUS.md from audit results."""
        lines = [
            "# Project Status",
            "",
            f"*Auto-generated by AIDLC code audit ({result.depth} scan)*",
            "",
            "## Current State",
            "",
            f"- **Project type**: {result.project_type}",
            f"- **Source files**: {result.source_stats.get('total_files', 0)}",
            f"- **Total lines**: {result.source_stats.get('total_lines', 0):,}",
            "",
        ]

        if result.frameworks:
            lines.append("## Frameworks & Dependencies")
            lines.append("")
            for fw in result.frameworks:
                lines.append(f"- {fw}")
            lines.append("")

        if result.modules:
            lines.append("## Modules")
            lines.append("")
            lines.append("| Module | Path | Files | Lines | Role |")
            lines.append("|--------|------|-------|-------|------|")
            for module in result.modules:
                mod = module if isinstance(module, ModuleInfo) else ModuleInfo.from_dict(module)
                lines.append(
                    f"| {mod.name} | {mod.path} | {mod.file_count} | "
                    f"{mod.line_count:,} | {mod.role} |"
                )
            lines.append("")

        if result.entry_points:
            lines.append("## Entry Points")
            lines.append("")
            for entry_point in result.entry_points:
                lines.append(f"- `{entry_point}`")
            lines.append("")

        if result.test_coverage:
            tc = (
                result.test_coverage
                if isinstance(result.test_coverage, CoverageInfo)
                else CoverageInfo.from_dict(result.test_coverage)
            )
            lines.append("## Test Coverage")
            lines.append("")
            lines.append(f"- **Test files**: {tc.test_files}")
            lines.append(f"- **Test functions**: {tc.test_functions}")
            lines.append(f"- **Estimated coverage**: {tc.estimated_coverage}")
            if tc.test_framework:
                lines.append(f"- **Framework**: {tc.test_framework}")
            lines.append("")

        runtime = result.runtime_checks or {}
        tier_results = runtime.get("tier_results", [])
        if tier_results:
            lines.append("## Runtime Audit Checks")
            lines.append("")
            lines.append(
                f"- **Overall runtime health**: "
                f"{'pass' if runtime.get('overall_passed') else 'fail'}"
            )
            if runtime.get("coverage_percent") is not None:
                lines.append(f"- **Observed coverage**: {runtime.get('coverage_percent')}%")
            for tier in tier_results:
                lines.append(
                    f"- **{tier.get('tier')}**: "
                    f"{'pass' if tier.get('passed') else 'fail'} "
                    f"({tier.get('duration_seconds', 0)}s)"
                )
            lines.append("")

        if result.features:
            lines.append("## Features")
            lines.append("")
            for feat in result.features:
                lines.append(f"- {feat}")
            lines.append("")

        if result.tech_debt:
            lines.append("## Known Tech Debt")
            lines.append("")
            debt_by_type = {}
            for item in result.tech_debt:
                td = item if isinstance(item, TechDebtItem) else TechDebtItem.from_dict(item)
                debt_by_type.setdefault(td.type, []).append(td)
            for dtype, items in sorted(debt_by_type.items()):
                lines.append(f"### {dtype.upper()} ({len(items)})")
                for td in items[:10]:
                    if td.type == "large_file":
                        lines.append(f"- `{td.file}`: {td.text}")
                    else:
                        lines.append(f"- `{td.file}:{td.line}`: {td.text}")
                if len(items) > 10:
                    lines.append(f"- ... and {len(items) - 10} more")
                lines.append("")

        by_ext = result.source_stats.get("by_extension", {})
        if by_ext:
            lines.append("## Source File Breakdown")
            lines.append("")
            for ext, count in by_ext.items():
                lines.append(f"- `{ext}`: {count} files")
            lines.append("")

        if result.degraded_stats:
            degraded_total = sum(result.degraded_stats.values())
            if degraded_total:
                lines.append("## Degraded Audit Reads")
                lines.append("")
                lines.append(
                    f"- The audit skipped or degraded {degraded_total} read/parse operation(s)."
                )
                for key, count in sorted(result.degraded_stats.items()):
                    if count:
                        lines.append(f"- `{key}`: {count}")
                lines.append("")
        return "\n".join(lines)

    def detect_conflicts(self, result) -> list[AuditConflict]:
        """Compare audit findings against existing user-provided docs."""
        conflicts = []
        generated_docs = set(result.generated_docs or [])

        arch_path = self.project_root / "ARCHITECTURE.md"
        if arch_path.exists() and "ARCHITECTURE.md" not in result.generated_docs:
            try:
                content = arch_path.read_text(errors="replace").lower()
                audit_types = set(result.project_type.lower().replace(",", " ").split())
                type_keywords = {
                    "python",
                    "javascript",
                    "typescript",
                    "rust",
                    "go",
                    "java",
                    "ruby",
                    "swift",
                    "kotlin",
                    "c++",
                    "c#",
                    "php",
                }
                mentioned_types = type_keywords & set(content.split())
                if (
                    mentioned_types
                    and not (mentioned_types & audit_types)
                    and result.project_type != "unknown"
                ):
                    conflicts.append(
                        AuditConflict(
                            doc_path="ARCHITECTURE.md",
                            field="project_type",
                            audit_value=result.project_type,
                            user_value=", ".join(sorted(mentioned_types)),
                            severity="error",
                        )
                    )

                for mod_name in re.findall(r"`(\w+)/`", content):
                    mod_path = self.project_root / mod_name
                    if not mod_path.exists() and mod_name not in EXCLUDE_DIRS:
                        conflicts.append(
                            AuditConflict(
                                doc_path="ARCHITECTURE.md",
                                field="missing_module",
                                audit_value=f"Directory '{mod_name}/' not found in repo",
                                user_value="Referenced in ARCHITECTURE.md",
                                severity="warning",
                            )
                        )
            except OSError:
                self.auditor._mark_degraded("doc_read_errors")

        if result.modules:
            user_docs_content = self.read_all_user_docs(generated_docs)
            if user_docs_content:
                for module in result.modules:
                    mod = module if isinstance(module, ModuleInfo) else ModuleInfo.from_dict(module)
                    if mod.file_count >= 5 and mod.role != "tests":
                        if mod.name.lower() not in user_docs_content.lower():
                            conflicts.append(
                                AuditConflict(
                                    doc_path="(no doc)",
                                    field="undocumented_module",
                                    audit_value=(
                                        f"Module '{mod.name}/' ({mod.file_count} files, "
                                        f"role: {mod.role}) exists but is not mentioned in any documentation"
                                    ),
                                    user_value="Not referenced",
                                    severity="warning",
                                )
                            )
        return conflicts

    def read_all_user_docs(self, generated_docs: set[str]) -> str:
        """Read all user-provided markdown docs for conflict checking."""
        parts = []
        for doc_name in ("README.md", "ARCHITECTURE.md", "ROADMAP.md", "DESIGN.md"):
            doc_path = self.project_root / doc_name
            if doc_path.exists() and doc_name not in generated_docs:
                try:
                    parts.append(doc_path.read_text(errors="replace"))
                except OSError:
                    self.auditor._mark_degraded("doc_read_errors")
        return "\n".join(parts)

    def write_conflicts_file(self, conflicts: list[AuditConflict]) -> None:
        """Write conflicts to .aidlc/CONFLICTS.md for user review."""
        aidlc_dir = self.project_root / ".aidlc"
        aidlc_dir.mkdir(exist_ok=True)
        path = aidlc_dir / "CONFLICTS.md"

        lines = [
            "# Audit Conflicts",
            "",
            "The code audit found the following conflicts with your existing documentation.",
            "Please review and resolve these before planning proceeds.",
            "",
            "After resolving, run `aidlc run --resume` to continue.",
            "",
        ]
        for idx, conflict in enumerate(conflicts, 1):
            item = (
                conflict
                if isinstance(conflict, AuditConflict)
                else AuditConflict.from_dict(conflict)
            )
            severity_label = "ERROR" if item.severity == "error" else "WARNING"
            lines.append(f"## {idx}. [{severity_label}] {item.field}")
            lines.append(f"- **Document**: `{item.doc_path}`")
            lines.append(f"- **Audit found**: {item.audit_value}")
            lines.append(f"- **Doc says**: {item.user_value}")
            lines.append("")

        path.write_text("\n".join(lines))
        self.logger.info(f"Wrote conflicts to {path}")

    def save_audit_json(self, result) -> None:
        """Save machine-readable audit result to .aidlc/audit_result.json."""
        aidlc_dir = self.project_root / ".aidlc"
        aidlc_dir.mkdir(exist_ok=True)
        path = aidlc_dir / "audit_result.json"
        with open(path, "w") as file_obj:
            json.dump(result.to_dict(), file_obj, indent=2)
        self.logger.info(f"Saved audit result to {path}")
